import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true });
const p = await b.newPage();
const errs = [];
p.on('pageerror', e => errs.push('PE: ' + e.message.slice(0,200)));
p.on('console', m => { if (/error/i.test(m.type())) errs.push('CE: ' + m.text().slice(0,200)); });
await p.goto('http://localhost:8000/user/login', { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForTimeout(2000);
await p.locator('input#username').fill('admin');
await p.locator('input#password').fill('ant.design');
await p.getByRole('button', { name: 'Login' }).click({ force: true });
await p.waitForURL(u => !new URL(u).pathname.startsWith('/user/login'), { timeout: 20000 });
await p.waitForTimeout(1500);
await p.goto('http://localhost:8000/list/table-list', { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForSelector('.ant-table-tbody tr', { timeout: 60000 });
await p.waitForTimeout(3000);
await p.evaluate(() => window.__wdpp__?.scanHydration?.());
await p.waitForTimeout(800);
const diag = await p.evaluate(() => {
  const w = window.__wdpp__;
  const rows = [...document.querySelectorAll('.ant-table-tbody tr')];
  const firstRowHTML = rows[0] ? rows[0].outerHTML.slice(0,400) : '(no rows)';
  const firstRowText = rows[0] ? rows[0].innerText.replace(/\s+/g,' ').trim().slice(0,200) : '';
  return { edges: w?.allEdges?.()?.length, fields: w?.fieldCount?.(), rowCount: rows.length, firstRowText, firstRowHTML };
});
console.log(JSON.stringify(diag, null, 1));
console.log('errors:', errs.slice(0,8).join('\n') || '(none)');
await b.close();
